//erroe
try{
    console.log(a);
}catch(err){
   // console.log(err);
   console.log("Something went wrong")
}